import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ClientNav from "@/components/ClientNav";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Freet.com",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          ><AppProvider>
              <ClientNav>
                {children}
              </ClientNav>
           <Toaster/>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
